config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  

  post 'favorites/create' => 'favorites#create'
  delete 'favorites/remove' => 'favorites#destroy'
  get 'bill' => 'searches#show'
  get 'favorite' => 'favorites#show'

delete 'favorites_remove_two' => 'favorites#destroy_search_bill'

  
  get 'searches/', to: 'searches#index'
  
  get 'searches/sort', to: 'searches#sort'
  get 'searches/search', to: 'searches#search'
  get 'users/search', to: 'searches#search'
  
  
  get '/welcome/search', to: 'searches#search'
  get '/search', to: 'searches#search'
  
  get 'sort', to: 'searches#sort' 
  
  get 'welcome/index'

  get 'welcome/about'

  get 'index/about'
  
  root 'welcome#index'
  
  get 'members/:chamber', to: 'members#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  
  validates :bill_id, uniqueness: { scope: :user_id, :message => "This bill is already saved." }
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    skip_before_filter :verify_authenticity_token

    before_action :authenticate_user_fav, only: [:create, :destroy] 
    
    include HTTParty
    
    def show

        @favorite = Favorite.find(params[:format]) 
    
        bill_slug = @favorite.bill_id.split('-')[0]
        congress = @favorite.bill_id.split('-')[1]
        @response = HTTParty.get('https://api.propublica.org/congress/v1/'+congress+'/bills/'+bill_slug+'.json', headers: {'X-API-Key' => 'kPp4zjf2X6vnYw81m5WND22ZcsLJAKYKmQsleEiR'})['results'][0]
        
        @favorite.status = @response['active']
        @favorite.save
        
        @actions = []
        @response['actions'].each do |action|
            @action  = Action.new(
                action_id: action['id'],
                chamber: action['chamber'],
                action_type: action['action_type'],
                date: action['datetime'],
                description: action['description']
            )
            @actions << @action
        end 
        
        @votes = []
        @response['votes'].each do |vote|
            @description = HTTParty.get(vote['api_url'], headers: {'X-API-Key' => 'kPp4zjf2X6vnYw81m5WND22ZcsLJAKYKmQsleEiR'})['results']['votes']['vote']['description']
            @vote  = Vote.new(
                chamber: vote['chamber'],
                date: vote['date'],
                time: vote['time'],
                roll_call: vote['roll_call'],
                question: vote['question']+"<br><u>Description</u><br>"+@description,
                # vote['question'],
                result: vote['result'],
                yea: vote['total_yes'],
                nay: vote['total_no'],
                not_voting: vote['total_not_voting'],
                api_url: vote['api_url']        
            )
            @votes << @vote
        end 
        
        rescue ActiveRecord::RecordNotFound
        redirect_to users_show_path, :flash => { :alert2 => "Record not found." }
    end 
   
    def create

        @bill = Bill.find(params[:id])
                
        @favorite  = Favorite.new(
            bill_id: @bill.bill_id,
            title: @bill.title,
            summary: @bill.summary,
            date: @bill.date,
            sponsor: @bill.sponsor,
            sponsor_state: @bill.sponsor_state,
            sponsor_party: @bill.sponsor_party,
            status: @bill.status,
            link: @bill.link
        )
        @favorite.user = current_user
        
        if @favorite.save
            # flash[:notice] = "Bill saved successfully."
        else
            if @favorite.errors.messages.empty?
                flash[:alert2] = "Bill could not be saved"
            else 
                flash[:alert2] = @favorite.errors.messages.first[1][0]
            end 
        end

        redirect_to params[:rdpath]
   end 
    
    def destroy
        @user = User.find(current_user)
        @favorite = Favorite.find(params[:id])
        
        if @favorite.destroy
            # flash[:notice] = "Bill was deleted from your saved bills."
            redirect_to users_show_path
        else
            flash[:alert2] = "Bill couldn't be deleted. Try again."
            redirect_to users_show_path
        end
    end
    
    def destroy_search_bill
        @bill = Bill.find(params[:format])
        @favorite = Favorite.where(bill_id: @bill.bill_id).first
        if @favorite.destroy
            # flash[:notice] = "Bill was deleted from your saved bills."
            redirect_to params[:rdpath]
        else
            flash[:alert2] = "Bill couldn't be deleted. Try again."
            redirect_to params[:rdpath]
        end
    end 
    
    private 

    def authenticate_user_fav 
        if !current_user
            flash[:alert] = "You need to be logged in to save bills."
            redirect_to searches_search_path
        end 
    end
    
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_new.html.erb
<% if user_signed_in? %>

  <% @bill = Bill.find(bill.id) %>
  
  <%= link_to bill.title, bill, class: "bill-link" %></br>
  <table class="search-layout">
    <tr>
      <td>Status:</td>
      <% if @bill.status == true %>
        <td><i class="fa fa-toggle-on" aria-hidden="true"></i>Active</td>
      <% else %>
        <td><i class="fa fa-toggle-off" aria-hidden="true"></i>Not Active</td>
      <% end %>
    </tr>
    <tr>
      <td>Sponsor:</td>
      <td><b><%= @bill.sponsor_party %></b>, <%= @bill.sponsor %> - <%= @bill.sponsor_state %></td>
    </tr>
    <tr>
      <td>Introduced:</td>
      <td><%= @bill.date.to_date.strftime("%B %d, %Y") %></td>
    </tr>
  </table>

  <%= form_tag url_for(:controller => "favorites", :action => "create"), :method => :POST do %>
    <div class="form-group" style="margin-bottom: 20px">
      <%= hidden_field_tag :rdpath , local_assigns[:rdpath]  %>
      <%= hidden_field_tag :id , @bill.id %>
      <%if !current_user %>
          <%= button_tag(type: "submit", class: "btn btn-default btn-save") do %>
            <i class="fa fa-star" aria-hidden="true" style="padding-right: 5px"></i> Save
          <% end %>
      <% else %>
          <% if current_user.favorites.where(bill_id: @bill.bill_id).present? %>
            <%= link_to "Unsave", favorites_remove_two_path(@bill, rdpath: searches_search_path), method: "delete", class: "btn btn-default btn-unsave" %>
          <% else %>
              <%= button_tag(type: "submit", class: "btn btn-default btn-save") do %>
                  <i class="fa fa-star" aria-hidden="true" style="padding-right: 5px"></i> Save
              <% end %>
          <% end %>
      <% end %>
    </div>
  <% end %>

<% else %>

  <p><%= link_to bill.title, bill_path(:bill_id=>bill.bill_id), class: "bill-link" %></br>
  
  <table class="search-layout">
    <tr>
      <td>Status:</td>
      <% if bill.status == true %>
        <td><i class="fa fa-toggle-on" aria-hidden="true"></i>Active</td>
      <% else %>
        <td><i class="fa fa-toggle-off" aria-hidden="true"></i>Not Active</td>
      <% end %>
    </tr>
    <tr>
      <td>Sponsor:</td>
      <td><b><%= bill.sponsor_party %></b>, <%= bill.sponsor %> - <%= bill.sponsor_state %></td>
    </tr>
    <tr>
      <td>Introduced:</td>
      <td><%= bill.date.to_date.strftime("%B, %d, %Y") %></td>
    </tr>
  </table>
  
  <%= link_to new_user_session_path(:alert=>true), class: "btn btn-default btn-save" do %>
    <i class="fa fa-star" aria-hidden="true" style="padding-right: 5px"></i> Save
  <% end %>

<% end %>

app/views/favorites/_newSlim.html.erb
<p></p>

<% @bill = Bill.find(bill.id) %>

<%= form_tag url_for(:controller => "favorites", :action => "create"), :method => :POST do %>
    <div class="form-group">
        <%= hidden_field_tag :rdpath , local_assigns[:rdpath]  %>
        <%= hidden_field_tag :id , @bill.id %>
        <%if !current_user %>
            <%= button_tag(type: "submit", class: "btn btn-default btn-save") do %>
              <i class="fa fa-star" aria-hidden="true" style="padding-right: 5px"></i> Save
            <% end %>
        <% else %>
            <% if current_user.favorites.where(bill_id: @bill.bill_id).present? %>
              <%= link_to "Unsave", favorites_remove_two_path(@bill, rdpath: bill_path(@bill)), method: "delete", class: "btn btn-default btn-unsave" %>
            <% else %>
                <%= button_tag(type: "submit", class: "btn btn-default btn-save") do %>
                    <i class="fa fa-star" aria-hidden="true" style="padding-right: 5px"></i> Save
                <% end %>
            <% end %>
        <% end %>
    </div>
<% end %>

app/views/favorites/_remove.html.erb
<% @favorite = Favorite.find(favorite.id) %>
<!-- need this, or can just pass favorite.id ? -->

<%= form_tag url_for(:controller => "favorites", :action => "destroy"), :method => :DELETE do %>
 <div class="form-group" style="margin-bottom: 20px;">
    <%= hidden_field_tag :id , @favorite.id %>
    
    <div class="form-group">
        <%= submit_tag "Unsave", class: "btn btn-default btn-unsave" %>
    </div>
    
 </div>
<% end %>

app/views/favorites/show.html.erb
<div class="row page-row">

  <div class="col-md-6">
    <h5>Title</h5>
    <p><%= @favorite.title %></p>
      
    <% if @favorite.summary != "" %>
      <h5>Summary</h5>
      <p class="text-justify"><%= @favorite.summary %></p>
    <% end %>
    
    <div style="float: left; margin-right:20px">
      <h5>Status</h5>
        <% if @favorite.status == true %>
          <td><i class="fa fa-toggle-on" aria-hidden="true"></i>Active</td>
        <% else %>
          <td><i class="fa fa-toggle-off" aria-hidden="true"></i>Not Active</td>
        <% end %>
    </div>
      
    <div style="float: left;">
      <h5>Sponsor</h5>
      <b><%= @favorite.sponsor_party %></b>, <%= @favorite.sponsor %> - <%= @favorite.sponsor_state %>
    </div>
      
    <br style="clear: left;" />
    
    <%= render 'favorites/remove', favorite: @favorite %><p></p>
  </div>
  
  <div class="col-md-6">
    <div class="billWidg">
      <h5>Bill Status by GovTrack.us</h5>
      <div class="bill-widget"><%= @favorite.link.html_safe %></div>
    </div>
  </div>
    
</div>

<div class="row page-row">
  
  <div class="col-md-4 col-sm-6">

    <h5>Actions</h5> 
    <% @actions.each do |action| %>
      <table class="search-layout bill-layout">
        <% if action.chamber != nil %>
        <tr>
          <td>Chamber:</td>
          <td><%= action.chamber %></td>
        </tr>
        <% end %>
        <tr>
          <td>Type:</td>
          <td><%= action.action_type %></td>
        </tr>
        <tr>
          <td>Date:</td>
          <td><%= action.date %></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td><%= action.description %></td>
        </tr>
        <tr><hr></tr>
      </table> 
    <% end %>
  
  </div>

  <div class="col-md-4 col-sm-6">
    
    <% if @votes.first != nil %>
      <h5>Votes</h5> 
    <% end %>
    <% @votes.each do |vote| %>
      <table class="search-layout bill-layout">
        <tr>
          <td>Chamber:</td>
          <td><%= vote.chamber %></td>
        </tr>
        <tr>
          <td>Date:</td>
          <td><%= vote.date %></td>
        </tr>
        <tr>
          <td>Question:</td>
          <td><%= vote.question.html_safe %></td>
        </tr>
        <tr>
          <td>Result:</td>
          <td><%= vote.result %></td>
        </tr>
        <tr><hr></tr>
      </table> 
    <% end %>
  
  </div>
  
  <div class="col-md-4">
  </div>

</div>