config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  

  post 'favorites/create' => 'favorites#create'
  delete 'favorites/remove' => 'favorites#destroy'
  get 'bill' => 'searches#show'
  get 'favorite' => 'favorites#show'

delete 'favorites_remove_two' => 'favorites#destroy_search_bill'

  
  get 'searches/', to: 'searches#index'
  
  get 'searches/sort', to: 'searches#sort'
  get 'searches/search', to: 'searches#search'
  get 'users/search', to: 'searches#search'
  
  
  get '/welcome/search', to: 'searches#search'
  get '/search', to: 'searches#search'
  
  get 'sort', to: 'searches#sort' 
  
  get 'welcome/index'

  get 'welcome/about'

  get 'index/about'
  
  root 'welcome#index'
  
  get 'members/:chamber', to: 'members#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :searches
  has_many :bills
  has_many :favorites
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :auth_user, only: [:show] 

  def show
    @user = User.find(current_user) 
    @favorites = @user.favorites
  end

private
  
  def auth_user
    if !user_signed_in?
      redirect_to root_path
      flash[:alert] = "You need to be signed in to access 'My Bills'."
    end 
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
<div class="row page-row">

    <div class="col-md-4 col-md-push-8">
    
        <%= render 'searches/form' %>

    </div>

    <div class="col-md-8 col-md-pull-4">
        <h2>Saved Bills <span style="font-size:.65em">(<%= current_user.email %>)</span></h2>

        <% @user.favorites.each do |favorite| %>
        
            <%= link_to favorite.title, favorite_path(:format => favorite.id), class: "bill-link" %>
            
            <table class="search-layout">
              <tr>
                <td>Status:</td>
                <% if favorite.status == true %>
                  <td><i class="fa fa-toggle-on" aria-hidden="true" style="color:#00b900; margin-right:7px"></i>Active</td>
                <% else %>
                  <td><i class="fa fa-toggle-off" aria-hidden="true" style="margin-right:7px"></i>Not Active</td>
                <% end %>
              </tr>
              <tr>
                <td>Sponsor:</td>
                <td><b><%= favorite.sponsor_party %></b>, <%= favorite.sponsor %> - <%= favorite.sponsor_state %></td>
              </tr>
            </table>
        
            <%= render 'favorites/remove', favorite: favorite %>
        
        <% end %>

    </div>

</div>
</div>