config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  

  post 'favorites/create' => 'favorites#create'
  delete 'favorites/remove' => 'favorites#destroy'
  get 'bill' => 'searches#show'
  get 'favorite' => 'favorites#show'

delete 'favorites_remove_two' => 'favorites#destroy_search_bill'

  
  get 'searches/', to: 'searches#index'
  
  get 'searches/sort', to: 'searches#sort'
  get 'searches/search', to: 'searches#search'
  get 'users/search', to: 'searches#search'
  
  
  get '/welcome/search', to: 'searches#search'
  get '/search', to: 'searches#search'
  
  get 'sort', to: 'searches#sort' 
  
  get 'welcome/index'

  get 'welcome/about'

  get 'index/about'
  
  root 'welcome#index'
  
  get 'members/:chamber', to: 'members#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liberty Hawk</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
      
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Archivo" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Archivo:400,700" rel="stylesheet">
</head>
<body>
    
  <nav class="navbar navbar-default navbar-static-top navbar-custom">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
      
        <%= link_to root_path, :class =>"navbar-brand", :style =>"padding-top:6px" do %>
          <%= image_tag "title.png" %>
        <% end %>
      </div>
      
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li style="padding-top: 5px; padding-left:14px">
              <form action="search" accept-charset="UTF-8" method="get">
                <div class="form-group">
                  <table>
                    <tr>
                      <td><input type="text" name="subject" class="form-control input-sm" style="min-width:225px;" /></td>
                      <td>
                        <button type="submit" name="Search" value="Search" class="btn btn-basic btn-sm" style="margin: 0 10px 0 10px;">
                          <i class="fa fa-search" aria-hidden="true"></i>
                        </button>
                      </td>
                    </tr>
                  </table>
                </div>
              </form>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Login
              <% end %>
            </li>
          <% else %>   
            <li><%= link_to "Search", searches_search_path %></li>
            <li><%= link_to "Favorites", users_show_path %></li>
            <li>
              <%= link_to destroy_user_session_path do %>
              <span class="glyphicon glyphicon-log-out"></span> Logout
              <% end %>
            </li> 
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
    
    
  <div class="container">
    <div class="wrapper">
      <% if flash[:notice] %>
        <div class="alert alert-success wrap">  
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:danger] %>
        <div class="alert alert-danger wrap">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:danger] %>
        </div>
      <% elsif flash[:alert2] %>
        <div class="alert alert-warning wrap">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert2].html_safe %>
        </div>
      <% end %>
              
      <%= yield %>
    </div>
  </div>


  <div id="footer" class="footer ><div>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> 2017 Vidya Neni All Rights Reserved</div></div>
  <div class="scroll-top visible-xs visible-sm">
      <a class="btn btn-primary page-scroll" href="#">
          <i class="fa fa-chevron-up"></i>
      </a>
  </div>

  <script>
  
  // function to get last word of search history panel heading, and apply css and an onclick function to it. 
  function lastWord() {
  	$('div#historyHeader').html(function(){	
  		// separate the text by spaces
  		var text= $(this).text().split(' ');
  		// drop the last word and store it in a variable
  		var last = text.pop();
  		// join the text back and if it has more than 1 word add the span tag
  		// to the last word
  		return text.join(" ") + (text.length > 0 ? ' <p class="last" style="float:right" onclick="toggleHistory();">'+last+'</p>' : last);   
  	});
  }
  
  // function to toggle display of the history panel body and heading content
  function toggleHistory() {
      var x = document.getElementById("history");
      var z = document.getElementById("historyHeader");
      if (x.style.display === "none" || z.textContent === 'Last 10 searches Show') {
          x.style.display = "block";
          z.textContent="Last 10 searches Hide";
      } 
      else {
          x.style.display = "none";
          z.textContent="Last 10 searches Show";
      }
  	
  	// call of last word function to update the last word of the history panel heading (make it a link)
    lastWord();
  }

  // call of last word function to update the last word of the history panel heading on page load
  jQuery(document).ready(lastWord());

  var hasScrollbar = window.innerWidth > document.documentElement.clientWidth;
  if (hasScrollbar) {
    var f = document.getElementById("footer");
    f.style.position="relative";
  }
  
  
  $(document).ready(function(){
      //Check to see if the window is top if not then display button
      $(window).scroll(function(){
          if ($(this).scrollTop() > 100) {
              $('.page-scroll').fadeIn();
          } else {
              $('.page-scroll').fadeOut();
          }
      });
    
    // jQuery for page scrolling feature
    $('.page-scroll').click(function() {
        $('html, body').animate({scrollTop : 0},800);
          return false;
    });
  });
 
  </script>

</body>
</html>